include:
  - path: caddy/docker-compose.yml
    env_file: .env
  - path: vw/docker-compose.yml
    env_file: .env
  - path: rclone/docker-compose.yml
    env_file: .env
  - path: copyparty/docker-compose.yml
    env_file: .env
  - path: navidrome/docker-compose.yml
    env_file: .env
  # - path: owui/docker-compose.yml
  #   env_file: .env

networks:
  vw:
  copyparty:
  navidrome:
  # owui:
