include:
  # common services
  - path: caddy/docker-compose.yml
    env_file: .env
  - path: cloudflared/docker-compose.yml
    env_file: .env
  - path: rclone/docker-compose.yml
    env_file: .env
  # /common services

  - path: vw/docker-compose.yml
    env_file: .env
  - path: copyparty/docker-compose.yml
    env_file: .env
  - path: navidrome/docker-compose.yml
    env_file: .env
  - path: picard/docker-compose.yml
    env_file: .env
  - path: downloaders/docker-compose.yml
    env_file: .env
  - path: immich/docker-compose.yml
    env_file:
      - .env
      - ./immich/.env
  - path: linkwarden/docker-compose.yml
    env_file:
      - .env
      - ./linkwarden/.env
  - path: pihole/docker-compose.yml
    env_file:
      - .env
      - ./pihole/.env
  - path: borg/docker-compose.yml
    env_file: .env
  - path: scrutiny/docker-compose.yml
    env_file: .env
  # - path: owui/docker-compose.yml
  #   env_file: .env

networks:
  cloudflared:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

  vw:
  copyparty:
  navidrome:
  picard:
  slskd:
  transmission:
  aria2:
  immich-front:
  immich-back:
  linkwarden-front:
  linkwarden-back:
  pihole:
  scrutiny:
  # owui:
