services:
  caddy:
    build: .
    container_name: caddy
    restart: always
    networks:
      - cloudflared
      - crowdsec-front

      - vw
      - copyparty
      - navidrome
      - picard
      - immich-front
      - geopulse-front
      - hauk-front
      - linkwarden-front
      - slskd
      - transmission
      - aria2
      - pyload
      - metube
      - pihole
      - scrutiny
      - miniflux-front

    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ${APP_DATA:?APP_DATA not set}/caddy/config:/config
      - ${APP_DATA:?APP_DATA not set}/caddy/data:/data
      - ${APP_DATA:?APP_DATA not set}/caddy/static:/static:ro
    environment:
        - SERVICE_DOMAIN=${SERVICE_DOMAIN:?SERVICE_DOMAIN not set}
        - PERSONAL_DOMAIN=${PERSONAL_DOMAIN:?}
    env_file: caddy.env

  caddy-build-static:
    profiles:
      - do-not-start
    image: alpine:latest
    container_name: caddy-build-static
    volumes:
      - ${APP_DATA:?APP_DATA not set}/caddy/static:/static
      - ./build-static.sh:/build-static.sh:ro
    tmpfs:
      - /tmp
    command: /bin/sh /build-static.sh
    restart: on-failure:3
