services:
  picard:
    profiles:
      - do-not-start
    container_name: picard
    image: mikenye/picard:latest
    restart: "no"
    networks:
        - picard
    ports:
      # vnc access
      - "6101:5900"
    volumes:
      - "${APP_DATA:?APP_DATA not set}/picard:/config:rw"
      - "./plugins/lrcget.py:/config/xdg/config/MusicBrainz/Picard/plugins/lrcget.py"

      - "${MUSIC_ROOT_PATH:?}:/music-root:rw"
