services:
  picard:
    profiles:
      - do_not_start
    container_name: picard
    image: mikenye/picard:latest
    restart: "no"
    networks:
        - picard
    volumes:
      - "${APP_DATA:?APP_DATA not set}/picard:/config:rw"
      - "./plugins/lrcget.py:/config/xdg/config/MusicBrainz/Picard/plugins/lrcget.py"

      - "${MUSIC_LIBRARY_PATH:?MUSIC_LIBRARY_PATH not set}:/storage:rw"
      - "${MUSIC_STAGING_PATH:?MUSIC_STAGING_PATH not set}:/music-staging:rw"
