services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    restart: always
    networks:
      - navidrome
    expose:
      - "4533"
    volumes:
      - "${APP_DATA:?}/navidrome:/data"
      - "${MUSIC_LIBRARY_PATH:?}:/music:ro"
      - "${MUSIC_STAGING_PATH:?}:/music-staging"
    environment:
      # - ND_LOGLEVEL=debug
      - ND_PLUGINS_ENABLED=true
      - ND_PLUGINS_AUTORELOAD=true
      - ND_AGENTS=audiomuseai,deezer,lastfm,listenbrainz
      - ND_ENABLEINSIGHTSCOLLECTOR=false
      - ND_ENABLESHARING=true
      - ND_SHAREURL=https://music.${PERSONAL_DOMAIN:?}
      - ND_PID_ALBUM=albumartistid,album,albumversion,releasedate
      - ND_LISTENBRAINZ_BASEURL=https://lb-proxy.${SERVICE_DOMAIN:?SERVICE_DOMAIN not set}/1/

  navidrome-octo-fiesta:
#     # 415198f is releases/v0.6
#    image: ghcr.io/v1ck3s/octo-fiesta:dev
#    build: https://github.com/kamaeff/octo-fiesta.git#feature/refactor-basedownloadservice
    build: ../../programming/octo-fiesta
    container_name: navidrome-octo-fiesta
    user: 1000:1000
    restart: always
    networks:
      - navidrome
    expose:
      - "8080"
    volumes:
      - "${MUSIC_STAGING_PATH:?}/octo-fiesta:/app/downloads"
    tmpfs: /tmp
    env_file:
      - octo-fiesta.env
