services:
  arpeggi-tmp-navidrome:
    image: deluan/navidrome:latest
    container_name: arpeggi-tmp-navidrome
    user: 1000:1000 # should be owner of volumes
    restart: always
    networks:
      - arpeggi-tmp-navidrome
    expose:
      - "4533"
    volumes:
      - "${APP_DATA:?}/arpeggi-tmp-navidrome/data:/data"
      - "${MUSIC_ROOT_PATH:?}/library:/music:ro"
      - "${APP_DATA:?}/arpeggi-tmp-navidrome/staging-library:/music-staging"
    environment:
      # - ND_LOGLEVEL=debug
      - ND_ENABLEINSIGHTSCOLLECTOR=false
      - ND_ENABLESHARING=false
      - ND_PID_ALBUM=albumartistid,album,albumversion,releasedate

  arpeggi-tmp-octo-fiesta:
#     # 415198f is releases/v0.6
#    image: ghcr.io/v1ck3s/octo-fiesta:dev
#    build: https://github.com/kamaeff/octo-fiesta.git#feature/refactor-basedownloadservice
    build: ../../programming/octo-fiesta
    container_name: arpeggi-tmp-octo-fiesta
    user: 1000:1000
    restart: always
    networks:
      - arpeggi-tmp-navidrome
    expose:
      - "8080"
    volumes:
      - "${APP_DATA:?}/arpeggi-tmp-navidrome/staging-library:/app/downloads"
    tmpfs: /tmp
    env_file:
      - octo-fiesta.env
