FROM rclone/rclone:latest

RUN apk update
# RUN apk add busybox-extras
RUN apk add curl

RUN [ "mkdir", "-p", "/config/rclone_example" ]
COPY rclone.conf /config/rclone_example/rclone.conf

COPY entrypoint.sh /bin/entrypoint.sh
RUN [ "chmod", "+x", "/bin/entrypoint.sh" ]

ENTRYPOINT [ "/bin/entrypoint.sh" ]
