FROM alpine/curl AS alpine-curl

FROM rclone/rclone:latest
COPY --from=alpine-curl /usr/bin/curl /usr/bin/curl

RUN [ "mkdir", "-p", "/config/rclone_example" ]
COPY rclone.conf /config/rclone_example/rclone.conf

COPY entrypoint.sh /bin/entrypoint.sh
RUN [ "chmod", "+x", "/bin/entrypoint.sh" ]

ENTRYPOINT [ "/bin/entrypoint.sh" ]
