[yandex]
type = yandex
token = {}

[google]
type = drive
scope = drive
token = {}
team_drive =

[union]
type = union
upstreams = yandex:rclone/rpi google:rclone/rpi
action_policy = all
create_policy = all
search_policy = all
