services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    user: 1000:1000
    restart: always
    networks:
      - slskd
    expose:
      - "5030"
#    unable to share behind cgnat :(
#    ports:
#      - "50300:50300"
    env_file:
      - slskd.env
    volumes:
      - "${APP_DATA:?APP_DATA not set}/slskd/app_data:/app"
      - "${APP_DATA:?APP_DATA not set}/slskd/incomplete:/app/incomplete"
      - "${MUSIC_STAGING_PATH:?MUSIC_STAGING_PATH not set}/slskd:/app/downloads"
      - "${MUSIC_LIBRARY_PATH:?MUSIC_LIBRARY_PATH not set}:/slskd-shares/navidrome:ro"

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    user: 1000:1000
    networks:
      - transmission
    expose:
      - "9091"
    ports:
      - 51413:51413/tcp
      - 51413:51413/udp
    environment:
      - HOST_WHITELIST=caddy
    env_file:
      - transmission.env
    volumes:
      - "${APP_DATA:?APP_DATA not set}/transmission/:/config"
      # - ""

    restart: always
