services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    user: 1000:1000
    restart: always
    networks:
      - slskd
    expose:
      - "5030"
#    unable to share behind cgnat :(
#    ports:
#      - "50300:50300"
    env_file:
      - slskd.env
    volumes:
      - "${APP_DATA:?}/slskd/app_data:/app"
      - "${APP_DATA:?}/slskd/incomplete:/app/incomplete"
      - "${MUSIC_ROOT_PATH:?}/staging/slskd:/app/downloads"
      - "${MUSIC_ROOT_PATH:?}/library:/slskd-shares/navidrome:ro"

  flood:
    image: jesec/flood
    container_name: flood
    user: 1000:1000
    networks:
      - transmission
    expose:
      - "3000"
    environment:
      - "HOME=/config"
      - "FLOOD_OPTION_allowedpath=/downloads"
    volumes:
      - "${DOWNLOADS_PATH:?}/torrents/:/downloads:ro"
      - "${APP_DATA:?}/flood:/config"
    restart: always

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    user: 1000:1000
    networks:
      - transmission
    expose:
      - "9091"
    ports:
      - 51413:51413/tcp
      - 51413:51413/udp
    env_file:
      - transmission.env
    volumes:
      - "${DOWNLOADS_PATH:?}/torrents/:/downloads"
      - "${APP_DATA:?}/transmission/:/config"
      # here can be added an optional watch directory
    restart: always

  aria2:
    build: ./aria2-build
    container_name: aria2
    user: 1000:1000
    networks:
      - aria2
    expose:
      - "6800"
    env_file:
      - aria2.env
    volumes:
      - "${APP_DATA:?}/aria2/:/aria2-data"
      - "${DOWNLOADS_PATH:?}/aria/:/downloads"
    restart: always

  pyload:
    image: linuxserver/pyload-ng:latest
    container_name: pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ${APP_DATA:?}/pyload:/config
      - ${DOWNLOADS_PATH:?}/pyload:/downloads
    networks:
      - pyload
    expose:
      - "8000"
#       - "9666" # optional Click'n'Load
    restart: always

  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    networks:
      - metube
    expose:
      - "8081"
    environment:
      - "LOGLEVEL=DEBUG"
      - "YTDL_OPTIONS={}"
      - "YTDL_OPTIONS_PRESETS_FILE=/etc/metube-ytdlp-presets.json"
    volumes:
      - "${DOWNLOADS_PATH:?}/youtube:/downloads"
      - "${FILESHARE_PATH:?}/public/youtube-archive:/downloads/public-archive"
      - "./metube-ytdlp-presets.json:/etc/metube-ytdlp-presets.json:ro"
    tmpfs:
      - /downloads/tmpfs
    restart: always
