services:  
  vw:
    image: vaultwarden/server:latest
    container_name: vw
    restart: unless-stopped
    networks:
      - vw
    expose:
      - 80
    environment:
      - SIGNUPS_ALLOWED=false
      - PUSH_ENABLED=true
      - EXPERIMENTAL_CLIENT_FEATURE_FLAGS=ssh-key-vault-item,ssh-agent
    env_file: vw.env
    volumes:
      - ${APP_DATA:?APP_DATA not set}/vw/data:/data

  vw-backup:
    image: bruceforce/vaultwarden-backup
    container_name: vw-backup
    restart: on-failure
    init: true
    depends_on:
      - vw
    volumes:
      - ${APP_DATA:?APP_DATA not set}/vw/data:/data
      - ${APP_DATA:?APP_DATA not set}/vw/backup:/backup/

      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - BACKUP_ON_STARTUP=true
      - CRON_TIME=0 7 * * *
      - DELETE_AFTER=60
      - TIMESTAMP=true
      - BACKUP_DIR_PERMISSIONS=755
      - LOG_LEVEL=DEBUG
      - UID=0
      - GID=0
    env_file: vw-backup.env
