FROM eclipse-temurin:25-alpine
RUN mkdir /opt/app /import && apk add --no-cache zstd && wget -O /opt/app/photon.jar https://github.com/komoot/photon/releases/download/1.1.0/photon-1.1.0.jar

COPY entrypoint.sh /bin/entrypoint.sh
RUN chmod +x /bin/entrypoint.sh

EXPOSE 2322

WORKDIR /data
ENTRYPOINT ["/bin/entrypoint.sh"]
CMD ["serve"]
