services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    env_file: cloudflared.env
    restart: always
    networks:
      - cloudflared
