# set wider range of allowed methods
SecRule &TX:allowed_methods "@eq 0" \
    "id:10000001,\
    phase:1,\
    pass,\
    nolog,\
    setvar:'tx.allowed_methods=GET HEAD POST OPTIONS PATCH PUT DELETE'"
