# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  ps4-hb-store:
    container_name: ps4-hb-store
    build: ./build
    networks:
      - ps4-hb-store
    expose:
      - "6449"
    volumes:
      - "${DOWNLOADS_PATH:?DOWNLOADS_PATH not set}/:/pkg"
    restart: always
